### ISSUE TITLE
All web addresses return with 400: Bad Request

### ISSUE THREAD

**Issue by Brandon4466** [BlueAndi/esp-rgb-led-matrix#61] opened 2021-10-24 05:08 UTC
Hello, I don't really know how to go about finding out what exactly the problem is, all I have is that no matter what URL I use it gives me a 400 Bad Request error. How can I find what the exact problem is?

Here is what I have:
`bool StockPlugin::startHttpRequest()
{
    bool    status  = false;
    String  url     = String("https://cloud.iexapis.com/stable/stock/spy/quote?token=pk...");

    if (true == m_client.begin(url))
    {
        if (false == m_client.GET())
        {
            LOG_WARNING("GET %s failed.", url.c_str());
        }
        else
        {
            LOG_INFO("GET %s success.", url.c_str());
            status = true;
        }
    }

    return status;
}`

And here is the error
`1175672 | INFO | AsyncHttpClient.cpp | 242 | Host: cloud.iexapis.com
-- | -- | -- | -- | --
1175677 | INFO | AsyncHttpClient.cpp | 243 | Port: 443
1175678 | INFO | AsyncHttpClient.cpp | 244 | URI: /stable/stock/spy/quote?token=pk...
1175678 | INFO | AsyncHttpClient.cpp | 248 | Authorization: -
1175680 | INFO | StockPlugin.cpp | 203 | GET https://cloud.iexapis.com/stable/stock/spy/quote?token=pk...
1175844 | INFO | AsyncHttpClient.cpp | 459 | Connected.
1175920 | INFO | AsyncHttpClient.cpp | 514 | onData(): len = 456
1175921 | INFO | AsyncHttpClient.cpp | 523 | Rsp. HTTP-Version: HTTP/1.1
1175922 | INFO | AsyncHttpClient.cpp | 524 | Rsp. Status-Code: 400
1175925 | INFO | AsyncHttpClient.cpp | 525 | Rsp. Reason-Phrase: Bad Request
1175925 | INFO | AsyncHttpClient.cpp | 1111 | Rsp. header: Server: nginx
1175928 | INFO | AsyncHttpClient.cpp | 1111 | Rsp. header: Date: Sun, 24 Oct 2021 05:01:51 GMT
1175928 | INFO | AsyncHttpClient.cpp | 1111 | Rsp. header: Content-Type: text/html
1175929 | INFO | AsyncHttpClient.cpp | 1111 | Rsp. header: Transfer-Encoding: chunked
1175929 | INFO | AsyncHttpClient.cpp | 1111 | Rsp. header: Connection: close
1175930 | INFO | AsyncHttpClient.cpp | 1111 | Rsp. header: Strict-Transport-Security: max-age=15768000
1175931 | INFO | AsyncHttpClient.cpp | 897 | Chunk size is 248 byte.
1175931 | INFO | AsyncHttpClient.cpp | 897 | Chunk size is 0 byte.
1175932 | INFO | AsyncHttpClient.cpp | 978 | Rsp. chunked transfer finished.
1175933 | INFO | AsyncHttpClient.cpp | 477 | Disconnected.
1175951 | INFO | StockPlugin.cpp | 268 | STOCK to print null`

NOTE: I removed the token here, but it is in the file and pasting that URL in the web browser or using curl does return the right JSON file.

Any help would be very appreciated, thank you!

**Comment by 0ooYoo0** [comment] 2021-11-03 12:14
This is most probably caused by the (currently) missing support of HTTP**S** in the used AsyncTCP lib.

**Comment by BlueAndi** [comment] 2021-11-03 17:57
#61

**Comment by BlueAndi** [comment] 2021-11-03 20:58
Please check with the Development branch and post the log here.

**Comment by BlueAndi** [comment] 2021-11-15 22:39
@Brandon4466 Any progress?

**Comment by BlueAndi** [comment] 2021-11-18 21:16
Let's close the issue as there is no further support necessary.

**Closed by BlueAndi** 2021-11-18 21:16 UTC
Labels: SW Enhancement
